# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANT_BOX         = "generic/ubuntu2204"
VAGRANT_BOX_VERSION = "4.2.10"
CPUS_COUNT    = 1
MEMORY  = 1024
WIFI_NETWORK_INTERFACE = "enp3s0"
ETH_NETWORK_INTERFACE = ""
NFS_IP = "192.168.1.175"

Vagrant.configure(2) do |config|

  # Function to add network interface if not empty
  def add_network_interface(config, interface, ip)
    if interface && !interface.empty?
      config.vm.network "public_network", bridge: interface, ip: ip
    end
  end

  config.vm.provision "shell", path: "bootstrap.sh"
  # Kubernetes NFS Server
  config.vm.define "nfs" do |node|

    node.vm.box               = VAGRANT_BOX
    node.vm.box_check_update  = false
    node.vm.box_version       = VAGRANT_BOX_VERSION
    node.vm.hostname          = "nfs"

    # Add Ethernet network interface if not empty
    add_network_interface(node, ETH_NETWORK_INTERFACE, NFS_IP)
    # Add Wi-Fi network interface
    add_network_interface(node, WIFI_NETWORK_INTERFACE, NFS_IP)

    node.vm.provider :virtualbox do |v|
      v.name    = "nfs"
      v.memory  = MEMORY
      v.cpus    = CPUS_COUNT
      
    end

    node.vm.provider :libvirt do |v|
      v.memory  = MEMORY
      v.nested  = true
      v.cpus    = CPUS_COUNT
    end


  end

end
