# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANT_BOX         = "generic/ubuntu2204"
VAGRANT_BOX_VERSION = "4.2.10"
CPUS_COUNT    = 1
MEMORY  = 1024
STORAGE_SIZE = 40 * 1024

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"
  config.disksize.size = '50GB'
  # Kubernetes NFS Server
  config.vm.define "nfs" do |node|

    node.vm.box               = VAGRANT_BOX
    node.vm.box_check_update  = false
    node.vm.box_version       = VAGRANT_BOX_VERSION
    node.vm.hostname          = "nfs"

    node.vm.network "public_network", ip: "192.168.1.230" # Change to your network IP

    node.vm.provider :virtualbox do |v|
      v.name    = "nfs"
      v.memory  = MEMORY
      v.cpus    = CPUS_COUNT
      
    end

    node.vm.provider :libvirt do |v|
      v.memory  = MEMORY
      v.nested  = true
      v.cpus    = CPUS_COUNT
    end


  end

end
